project:
  type: book

lang: es

book:
  title: "Economía: una introducción"
  author: "Javier Abellán"
  date: "5/28/2026"
  chapters:
    - index.qmd
    - intro.qmd

    - part: "Parte I. Microeconomía"
      chapters:
        - mercado.qmd
        - produccion.qmd
        - competencia_perfecta.qmd
        - mercados_no_competitivos.qmd

    - part: "Parte II. Macroeconomía"
      chapters:
        - macro_produccion_empleo.qmd
        - macro_precios_balanza.qmd
        - consumo_ahorro_estado.qmd
        - finanzas.qmd
        - comercio_exterior.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: custom.css
  pdf:
    documentclass: scrreprt



